### ISSUE TITLE
Guide on how to install for noobs/non-techies. 

### ISSUE THREAD

**Issue by BCCarmy** [satoshilabs/bitcoin-abc#1]
### Describe the issue

Regular users who have the hardware and desire to run bitcore nodes, to support other users hardware wallets, for no charge, want to install this program, we just need similar guides to how the old version was installed, as previously there was an entire website dedicated to helping do so (https://bitcore.io/guides/full-node/). We are willing to donate our hard drives and computing power, we just need some guides to help us:

Tell us what should happen:

Can someone please make a guide for how to do so on ubuntu/windows/OSX

**Comment by karelbilek** [comment]
We don't have the resources for that. 

We are maintaining bitcore only because we need it for trezor webwallet and bitpay stopped caring, not because we really want to.

**Comment by prusnak** [comment]
Instructions haven't really changed since we forked the project, so you can still consult the original documentation.
