### ISSUE TITLE
Rebase on top of Bitcoin ABC version 0.16.0

### ISSUE THREAD

**Issue by bendelo** [satoshilabs/bitcoin-abc#2]
Please could you rebase on top of this branch?
https://github.com/Bitcoin-ABC/bitcoin-abc/tree/v0.16.0

**Comment by karelbilek** [comment]
Done, in 0.16.0 branch

**Comment by karelbilek** [comment]
https://github.com/satoshilabs/bitcoin-abc/tree/0.16.0-bitcore
