### ISSUE TITLE
when support bitcoin-abc 0.17.2 and later

### ISSUE THREAD

**Issue by Comer2020** [satoshilabs/bitcoin-abc#5]
hi, dear owner,
my question is when satoshi version of  bitcoin-abc will support new 0.17.2? 
after several bch hard fork, it seems that satoshi version 0.16.0 can not sync blocks with bch testnet properly. I am looking forward to receive you answer if you can. thanks very much!

**Comment by prusnak** [comment]
We don't support this project anymore.

**Comment by karelbilek** [comment]
Note the big "this is obsolete" in the readme
